# Makefile - lis3dsh sample
#
# Copyright (c) 2016, Freescale Semiconductor, Inc.
# Copyright (c) 2017, BayLibre, SAS.
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD ?= stm32f4_disco
CONF_FILE ?= prj.conf

include $(ZEPHYR_BASE)/Makefile.inc
